### ISSUE TITLE
panic: couldn't find task

### ISSUE THREAD

**Issue by cucaroach** [dominikh/gotraceui#110]
```
panic: couldn't find task

goroutine 12 [running]:
honnef.co/go/gotraceui/trace/ptrace.(*Trace).Task(0x140007c19e0, 0x30?)
        /Users/treilly/go/pkg/mod/honnef.co/go/gotraceui@v0.2.0/trace/ptrace/ptrace.go:1037 +0x88
main.userRegionSpanTooltip(0x14000098100, {{{0xea2, 0x9ac}, {0xea2, 0x9ac}}, {0x40000000, 0x40000000}, {0x10087cbd8, 0x140007b86d0}, {0xc11b4a51f7e16b80, ...}, ...}, ...)
        /Users/treilly/go/pkg/mod/honnef.co/go/gotraceui@v0.2.0/cmd/gotraceui/goroutine.go:1135 +0xf8
main.(*Track).Layout.func2.1(0x140000b2750?, {{{0xea2, 0x9ac}, {0xea2, 0x9ac}}, {0x40000000, 0x40000000}, {0x10087cbd8, 0x140007b86d0}, {0xc11b4a51f7e16b80, ...}, ...})
        /Users/treilly/go/pkg/mod/honnef.co/go/gotraceui@v0.2.0/cmd/gotraceui/timeline.go:751 +0xc4
honnef.co/go/gotraceui/theme.(*Window).Render(0x14000098100, 0x14001a46790?, {{0xc11b4a51f7e16b80, 0x19164e89c01, 0x100c75ee0}, {0x40000000, 0x40000000}, {0xea2, 0x9ac}, {0x0, ...}, ...}, ...)
        /Users/treilly/go/pkg/mod/honnef.co/go/gotraceui@v0.2.0/theme/window.go:87 +0x788
main.(*MainWindow).Run(0x140007c4000, 0x140007b8600)
        /Users/treilly/go/pkg/mod/honnef.co/go/gotraceui@v0.2.0/cmd/gotraceui/main.go:696 +0x520
main.main.func3()
        /Users/treilly/go/pkg/mod/honnef.co/go/gotraceui@v0.2.0/cmd/gotraceui/main.go:1301 +0x9c
created by main.main
        /Users/treilly/go/pkg/mod/honnef.co/go/gotraceui@v0.2.0/cmd/gotraceui/main.go:1299 +0x4f8
```

Playing with runtime/trace API, I have a trace file that has a trace.Task that may or not start in the trace and may or may not end in the trace which I'm guessing trips this code up.   It happens when I focus on the goroutine that created the Task.   I can share trace file if needed but its large (22mb/11mb zipped).

**Comment by whereswaldon** [comment]
I hit this bug previously and it is already fixed on the master branch. I don't think a release has come out that includes it yet though.

**Comment by dominikh** [comment]
whereswaldon is correct.
