### ISSUE TITLE
Clicking on a STW entry causes panic

### ISSUE THREAD

**Issue by dannykopping** [dominikh/gotraceui#131]
```
panic: unsupported type: *main.STW
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary
```

```bash
$ gotraceui --version
gotraceui v0.3.0
```

PS this tool looks amazing in general! So glad I found it, will definitely be playing with it more 🙂

**Comment by dannykopping** [comment]
Same for a GC entry

```go
panic: unsupported type: *main.GC
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary

goroutine 21 [running]:
gioui.org/internal/ops.PopOp(...)
	/Users/danny/go/pkg/mod/gioui.org@v0.0.0-20230611141527-3bb6cca15710/internal/ops/ops.go:257
gioui.org/op/clip.Stack.Pop({0x14000220cf0?, {0x1029ac644?, 0x140038109c8?}, 0x10298e25c?})
	/Users/danny/go/pkg/mod/gioui.org@v0.0.0-20230611141527-3bb6cca15710/op/clip/clip.go:105 +0x120
panic({0x102d53260?, 0x102deac88?})
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/panic.go:914 +0x218
gioui.org/internal/ops.PopOp(...)
	/Users/danny/go/pkg/mod/gioui.org@v0.0.0-20230611141527-3bb6cca15710/internal/ops/ops.go:257
gioui.org/op.TransformStack.Pop({{0x14003810b38?, 0x102984df4?}, 0x12d5bc850?, 0x14000220cf0?})
	/Users/danny/go/pkg/mod/gioui.org@v0.0.0-20230611141527-3bb6cca15710/op/op.go:239 +0x118
panic({0x102d53260?, 0x14002d92a90?})
	/opt/homebrew/Cellar/go/1.21.0/libexec/src/runtime/panic.go:914 +0x218
main.defaultObjectLink({0x102d40e60?, 0x140032db470?})
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/cmd/gotraceui/link.go:29 +0x18c
main.(*TextBuilder).DefaultLink(0x14002848fc0?, {0x102c6dfcb, 0x2}, {0x102d40e60, 0x140032db470})
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/cmd/gotraceui/main.go:1628 +0x38
main.(*SpansInfo).buildDefaultDescription(0x140033ee000, 0xc13491e5c8d7fe08?, {{{0x0, 0x0}, {0x1d4, 0x3f8}}, {0x40000000, 0x40000000}, {0x102decc60, 0x140003ce0c8}, ...})
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/cmd/gotraceui/span.go:282 +0xb88
main.(*SpansInfo).Layout.func3({{{0x0, 0x0}, {0x1d4, 0x3f8}}, {0x40000000, 0x40000000}, {0x102decc60, 0x140003ce0c8}, {0xc13491e5c8d7fe08, 0x8c1d2261, ...}, ...})
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/cmd/gotraceui/span.go:359 +0xd4
gioui.org/layout.Flex.Layout({0xf0?, 0xc?, 0x22?, 0x140?}, {{{0x1d4, 0x0}, {0x1d4, 0x485}}, {0x40000000, 0x40000000}, ...}, ...)
	/Users/danny/go/pkg/mod/gioui.org@v0.0.0-20230611141527-3bb6cca15710/layout/flex.go:99 +0x22c
main.(*SpansInfo).Layout(0x140033ee000, 0x1400011e240, {{{0x1d4, 0x0}, {0x1d4, 0x485}}, {0x40000000, 0x40000000}, {0x102decc60, 0x140003ce0c8}, ...})
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/cmd/gotraceui/span.go:315 +0x750
honnef.co/go/gotraceui/theme.ResizeStyle.Layout.Dumb.func4({{{0x1de, 0x0}, {0x1de, 0x48f}}, {0x40000000, 0x40000000}, {0x102decc60, 0x140003ce0c8}, {0xc13491e5c8d7fe08, 0x8c1d2261, ...}, ...})
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/theme/window.go:109 +0xb0
gioui.org/layout.Flex.Layout({0xaa?, 0x4?, 0x0?, 0x0?}, {{{0x0, 0x0}, {0x640, 0x48f}}, {0x40000000, 0x40000000}, ...}, ...)
	/Users/danny/go/pkg/mod/gioui.org@v0.0.0-20230611141527-3bb6cca15710/layout/flex.go:134 +0x550
gioui.org/x/component.(*Resize).Layout(0x1400011d2c0, {{{0x0, 0x0}, {0x640, 0x48f}}, {0x40000000, 0x40000000}, {0x102decc60, 0x140003ce0c8}, {0xc13491e5c8d7fe08, ...}, ...}, ...)
	/Users/danny/go/pkg/mod/gioui.org/x@v0.0.0-20230609201311-f4f65e94fa90/component/resizer.go:41 +0x3b0
honnef.co/go/gotraceui/theme.ResizeStyle.Layout({0x1400011d2c0?, {0x0?, 0x0?, 0x0?, 0x40?}}, 0x1400011e240, {{{0x0, 0x0}, {0x640, 0x48f}}, ...}, ...)
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/theme/theme.go:725 +0x21c
main.(*MainWindow).Run.func1(0x1400011e240, {{{0x0, 0x0}, {0x640, 0x48f}}, {0x40000000, 0x40000000}, {0x102decc60, 0x140003ce0c8}, {0xc13491e5c8d7fe08, ...}, ...})
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/cmd/gotraceui/main.go:948 +0x1bbc
honnef.co/go/gotraceui/theme.(*Window).Render.Dumb.func2({{{0x640, 0x48f}, {0x640, 0x48f}}, {0x40000000, 0x40000000}, {0x102decc60, 0x140003ce0c8}, {0xc13491e5c8d7fe08, 0x8c1d2261, ...}, ...})
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/theme/window.go:109 +0xb0
honnef.co/go/gotraceui/layout.PixelInset.Layout({0x10320a0a0?, 0x0?, 0x0?, 0x0?}, {{{0x640, 0x48f}, {0x640, 0x48f}}, {0x40000000, 0x40000000}, ...}, ...)
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/layout/layout.go:100 +0x240
honnef.co/go/gotraceui/theme.(*Window).Render(0x1400011e240, 0x14003814770?, {{0xc13491e5c8d7fe08, 0x8c1d2261, 0x10320a0a0}, {0x40000000, 0x40000000}, {0x640, 0x4b0}, {0x0, ...}, ...}, ...)
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/theme/window.go:173 +0x90c
main.(*MainWindow).Run(0x14000126000, 0x140003ce000)
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/cmd/gotraceui/main.go:640 +0x548
main.main.func3()
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/cmd/gotraceui/main.go:1303 +0x98
created by main.main in goroutine 1
	/Users/danny/go/pkg/mod/honnef.co/go/gotraceui@v0.3.0/cmd/gotraceui/main.go:1301 +0x5b4
```

**Comment by dominikh** [comment]
This should be fixed on the master branch. Can you confirm?

**Comment by dannykopping** [comment]
Confirmed! Sorry for the noise
