### ISSUE TITLE
panic while clicking right button somewhere in trace

### ISSUE THREAD

**Issue by korniltsev** [dominikh/gotraceui#163]
```
panic: attempted to get GoID from Proc resource ID
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary

goroutine 9 [running]:
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x925b20?, 0xaea460?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x925b20?, 0xaea460?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x925b20?, 0xaea460?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x925b20?, 0xaea460?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x925b20?, 0xaea460?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x925b20?, 0xc01861c270?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
golang.org/x/exp/trace.ResourceID.Goroutine(...)
	/home/korniltsev/go/pkg/mod/golang.org/x/exp@v0.0.0-20240613232115-7f521ea00fb8/trace/resources.go:173
main.processorTrackSpanContextMenu({0xaf36a0, 0xc04ba56460}, 0xc0000a9008)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/processor.go:119 +0x545
main.(*trackSpanInteractivity).Handle(0xc042519ad0, 0xc000108500, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, ...}, ...)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/timeline.go:1030 +0x128
main.(*Track).layoutMain.func2({0xaf36a0, 0xc04ba56460}, 0xc19ada16, 0x4386d095)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/timeline.go:733 +0x1d4
main.(*Track).layoutMain(0xc02723e0d0, 0xc000108500, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, ...}, ...)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/timeline.go:859 +0x2685
main.(*Track).Layout.func1(0x0?, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/timeline.go:624 +0x65
honnef.co/go/gotraceui/theme.Record(0xc000108500, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/theme.go:994 +0xa7
main.(*Track).Layout(0xc02723e0d0, 0xc000108500, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, ...}, ...)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/timeline.go:623 +0x308
main.(*Timeline).Layout(0xc027232930, 0xc000108500, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, ...}, ...)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/timeline.go:412 +0xc7a
main.(*Canvas).layoutTimelines(0xc0000a9008, 0xc000108500, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:1215 +0x5ba
main.(*Canvas).Layout.func1.3.2.1({{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, 0x846d513bd5, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:1005 +0x411
gioui.org/layout.Flex.Layout({0x79?, 0x17?, 0x73?, 0x0?}, {{{0x0, 0x346}, {0x51b, 0x346}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/layout/flex.go:134 +0x5f5
main.(*Canvas).Layout.func1.3.2(0xc000108500, {{{0x0, 0x346}, {0x51b, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:951 +0x23a
honnef.co/go/gotraceui/theme.ResizeStyle.Layout.Dumb.func4({{{0x0, 0x346}, {0x51b, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, 0x846d513bd5, ...}, ...})
	/home/korniltsev/github/gotraceui/theme/window.go:165 +0x39
gioui.org/layout.Flex.Layout({0xc8?, 0x97?, 0xa?, 0xc0?}, {{{0x0, 0x0}, {0x51b, 0x41c}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/layout/flex.go:134 +0x5f5
gioui.org/x/component.(*Resize).Layout(0xc0000a97c0, {{{0x0, 0x0}, {0x51b, 0x41c}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, ...}, ...}, ...)
	/home/korniltsev/go/pkg/mod/gioui.org/x@v0.4.0/component/resizer.go:41 +0x418
honnef.co/go/gotraceui/theme.ResizeStyle.Layout({0xc0000a97c0?, {0x0?, 0x41d80000?, 0x4251bf98?, 0xc0?}}, 0xc000108500, {{{0x0, 0x0}, {0x51b, 0x41c}}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/theme.go:753 +0x333
main.(*Canvas).Layout.func1.3({{{0x0, 0x0}, {0x51b, 0x41c}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, 0x846d513bd5, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:927 +0x15f
honnef.co/go/gotraceui/layout.Rigids({{{0x0, 0x0}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, 0x846d513bd5, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/layout/layout.go:164 +0x436
main.(*Canvas).Layout.func1(0xc0000a9008, 0xc000108500, {{{0x0, 0x0}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:889 +0x4cd
main.(*Canvas).Layout(0xc0000a9008, 0xc000108500, {{{0x0, 0x0}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:1124 +0x1b8e
main.(*TimelinesComponent).Layout(0x40a0000000000000?, 0x0?, {{{0x51b, 0x437}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:606 +0x39
main.(*MainWindow).renderMainScene.func1.1(0x1a0000000a?, {{{0x51b, 0x437}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:1029 +0x9b
honnef.co/go/gotraceui/theme.TabbedStyle.Layout.func1.4({{{0x51b, 0x0}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, 0x846d513bd5, ...}, ...})
	/home/korniltsev/github/gotraceui/theme/theme.go:971 +0x39
honnef.co/go/gotraceui/layout.Rigids({{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, 0x846d513bd5, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/layout/layout.go:164 +0x436
honnef.co/go/gotraceui/theme.TabbedStyle.Layout.func1(0x51b?, {{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, ...}, ...})
	/home/korniltsev/github/gotraceui/theme/theme.go:933 +0x16d
honnef.co/go/gotraceui/theme.Background.Layout({{0xa9968?, 0xc0?, 0x0?, 0x0?}}, 0xc000108500, {{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/util.go:65 +0x13e
honnef.co/go/gotraceui/theme.TabbedStyle.Layout({0xc0000a9968?, {0xc02619df40?, 0xc04251d650?, 0xc04251d568?}}, 0xc000108500, {{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/theme.go:932 +0x2d5
main.(*MainWindow).renderMainScene.func1(0xc000108500, {{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:1023 +0x185
honnef.co/go/gotraceui/theme.ResizeStyle.Layout.Dumb.func3({{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, 0x846d513bd5, ...}, ...})
	/home/korniltsev/github/gotraceui/theme/window.go:165 +0x39
gioui.org/layout.Flex.Layout({0x0?, 0x9d?, 0xa?, 0xc0?}, {{{0x0, 0x0}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/layout/flex.go:134 +0x5f5
gioui.org/x/component.(*Resize).Layout(0xc0000a9cf8, {{{0x0, 0x0}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, ...}, ...}, ...)
	/home/korniltsev/go/pkg/mod/gioui.org/x@v0.4.0/component/resizer.go:41 +0x418
honnef.co/go/gotraceui/theme.ResizeStyle.Layout({0xc0000a9cf8?, {0x1d1500?, 0xc0?, 0x4251de78?, 0xc0?}}, 0xc000108500, {{{0x0, 0x0}, {0x750, 0x456}}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/theme.go:753 +0x333
main.(*MainWindow).renderMainScene(0xc0000a9008, 0xc000108500, {{{0x0, 0x0}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, ...}, ...)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:1040 +0x82f
main.(*MainWindow).Run.func2(0xc000108500, {{{0x0, 0x0}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:858 +0x5ec
honnef.co/go/gotraceui/theme.(*Window).Layout.Dumb.func2({{{0x750, 0x456}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001386d0}, {0xc1a0c7d19a72cf0c, 0x846d513bd5, ...}, ...})
	/home/korniltsev/github/gotraceui/theme/window.go:165 +0x39
honnef.co/go/gotraceui/layout.PixelInset.Layout({0x467?, 0x3f8000003f800000?, 0xaed560?, 0xc0001386d0?}, {{{0x750, 0x456}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/korniltsev/github/gotraceui/layout/layout.go:103 +0x316
honnef.co/go/gotraceui/theme.(*Window).Layout(0xc000108500, 0xc000188680, {{0xc1a0c7d19a72cf0c, 0x846d513bd5, 0x102d580}, {0x3f800000, 0x3f800000}, {0x750, 0x467}, {0x0, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/window.go:288 +0x7d6
main.(*MainWindow).Run(0xc0000a9008)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:819 +0x508
main.main.func2()
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:1416 +0x1c
created by main.main in goroutine 1
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:1415 +0x59d

```

**Comment by korniltsev** [comment]
Built from source a47c61fbb6d0c322bf3db28b3461d0ce18d4720c

**Comment by korniltsev** [comment]
```
panic: runtime error: invalid memory address or nil pointer dereference
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary
	panic: stack push and pop must not cross macro boundary
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x8140fa]

goroutine 9 [running]:
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x925b20?, 0xaea460?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x925b20?, 0xaea460?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x925b20?, 0xaea460?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x925b20?, 0xaea460?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x925b20?, 0xaea460?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op.TransformStack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/op.go:239
panic({0x925b20?, 0xaea460?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
gioui.org/internal/ops.PopOp(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/internal/ops/ops.go:275
gioui.org/op/clip.Stack.Pop(...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/op/clip/clip.go:105
panic({0x950780?, 0xddece0?})
	/home/korniltsev/sdk/go1.22.4/src/runtime/panic.go:770 +0x132
main.Filter.couldMatchState({0x1e?, 0x1?}, {0x0?, 0x0?}, {0xc00cb06070?, 0xc00cb10000?})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/filter.go:113 +0xba
main.Filter.couldMatch({0x38?, 0xaed560?}, {0x715ba6e9c9f0?, 0xc0286464b0?}, {0xc00cb06070?, 0xc00cb10000?})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/filter.go:92 +0x31
main.Filter.Match({0xd?, 0x346?}, {0x715ba6e9c9f0, 0xc0286464b0}, {0xc00cb06070?, 0xc00cb10000?})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/filter.go:32 +0x45
main.(*Track).layoutMain.func2({0xaf36a0, 0xc0286464b0}, 0x426b1747, 0x449a4746)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/timeline.go:740 +0x28e
main.(*Track).layoutMain(0xc00cb10000, 0xc000188500, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, ...}, ...)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/timeline.go:879 +0x124d
main.(*Track).Layout.func1(0x0?, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/timeline.go:624 +0x65
honnef.co/go/gotraceui/theme.Record(0xc000188500, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/theme.go:994 +0xa7
main.(*Track).Layout(0xc00cb10000, 0xc000188500, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, ...}, ...)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/timeline.go:623 +0x308
main.(*Timeline).Layout(0xc00cb06070, 0xc000188500, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, ...}, ...)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/timeline.go:412 +0xc7a
main.(*Canvas).layoutTimelines(0xc0000a9008, 0xc000188500, {{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:1215 +0x5ba
main.(*Canvas).Layout.func1.3.2.1({{{0x50d, 0x346}, {0x50d, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, 0x2bb58c7d8, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:1005 +0x411
gioui.org/layout.Flex.Layout({0x79?, 0x17?, 0x73?, 0x0?}, {{{0x0, 0x346}, {0x51b, 0x346}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/layout/flex.go:134 +0x5f5
main.(*Canvas).Layout.func1.3.2(0xc000188500, {{{0x0, 0x346}, {0x51b, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:951 +0x23a
honnef.co/go/gotraceui/theme.ResizeStyle.Layout.Dumb.func4({{{0x0, 0x346}, {0x51b, 0x346}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, 0x2bb58c7d8, ...}, ...})
	/home/korniltsev/github/gotraceui/theme/window.go:165 +0x39
gioui.org/layout.Flex.Layout({0xc8?, 0x97?, 0xa?, 0xc0?}, {{{0x0, 0x0}, {0x51b, 0x41c}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/layout/flex.go:134 +0x5f5
gioui.org/x/component.(*Resize).Layout(0xc0000a97c0, {{{0x0, 0x0}, {0x51b, 0x41c}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, ...}, ...}, ...)
	/home/korniltsev/go/pkg/mod/gioui.org/x@v0.4.0/component/resizer.go:41 +0x418
honnef.co/go/gotraceui/theme.ResizeStyle.Layout({0xc0000a97c0?, {0x0?, 0x41d80000?, 0x2f2fbf98?, 0xc0?}}, 0xc000188500, {{{0x0, 0x0}, {0x51b, 0x41c}}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/theme.go:753 +0x333
main.(*Canvas).Layout.func1.3({{{0x0, 0x0}, {0x51b, 0x41c}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, 0x2bb58c7d8, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:927 +0x15f
honnef.co/go/gotraceui/layout.Rigids({{{0x0, 0x0}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, 0x2bb58c7d8, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/layout/layout.go:164 +0x436
main.(*Canvas).Layout.func1(0xc0000a9008, 0xc000188500, {{{0x0, 0x0}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:889 +0x4cd
main.(*Canvas).Layout(0xc0000a9008, 0xc000188500, {{{0x0, 0x0}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/canvas.go:1124 +0x1b8e
main.(*TimelinesComponent).Layout(0x40a0000000000000?, 0x0?, {{{0x51b, 0x437}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:606 +0x39
main.(*MainWindow).renderMainScene.func1.1(0x140000000a?, {{{0x51b, 0x437}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:1029 +0x9b
honnef.co/go/gotraceui/theme.TabbedStyle.Layout.func1.4({{{0x51b, 0x0}, {0x51b, 0x437}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, 0x2bb58c7d8, ...}, ...})
	/home/korniltsev/github/gotraceui/theme/theme.go:971 +0x39
honnef.co/go/gotraceui/layout.Rigids({{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, 0x2bb58c7d8, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/layout/layout.go:164 +0x436
honnef.co/go/gotraceui/theme.TabbedStyle.Layout.func1(0x51b?, {{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, ...}, ...})
	/home/korniltsev/github/gotraceui/theme/theme.go:933 +0x16d
honnef.co/go/gotraceui/theme.Background.Layout({{0xa9968?, 0xc0?, 0x0?, 0x0?}}, 0xc000188500, {{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/util.go:65 +0x13e
honnef.co/go/gotraceui/theme.TabbedStyle.Layout({0xc0000a9968?, {0xc02ef53480?, 0xc02f2fd650?, 0xc02f2fd568?}}, 0xc000188500, {{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/theme.go:932 +0x2d5
main.(*MainWindow).renderMainScene.func1(0xc000188500, {{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:1023 +0x185
honnef.co/go/gotraceui/theme.ResizeStyle.Layout.Dumb.func3({{{0x51b, 0x0}, {0x51b, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, 0x2bb58c7d8, ...}, ...})
	/home/korniltsev/github/gotraceui/theme/window.go:165 +0x39
gioui.org/layout.Flex.Layout({0x0?, 0x9d?, 0xa?, 0xc0?}, {{{0x0, 0x0}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/korniltsev/go/pkg/mod/gioui.org@v0.4.1/layout/flex.go:134 +0x5f5
gioui.org/x/component.(*Resize).Layout(0xc0000a9cf8, {{{0x0, 0x0}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, ...}, ...}, ...)
	/home/korniltsev/go/pkg/mod/gioui.org/x@v0.4.0/component/resizer.go:41 +0x418
honnef.co/go/gotraceui/theme.ResizeStyle.Layout({0xc0000a9cf8?, {0x6b45a0?, 0xc0?, 0x2f2fde78?, 0xc0?}}, 0xc000188500, {{{0x0, 0x0}, {0x750, 0x456}}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/theme.go:753 +0x333
main.(*MainWindow).renderMainScene(0xc0000a9008, 0xc000188500, {{{0x0, 0x0}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, ...}, ...)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:1040 +0x82f
main.(*MainWindow).Run.func2(0xc000188500, {{{0x0, 0x0}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, ...}, ...})
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:858 +0x5ec
honnef.co/go/gotraceui/theme.(*Window).Layout.Dumb.func2({{{0x750, 0x456}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, {0xaed560, 0xc0001b86d0}, {0xc1a0c8c1de7d36f2, 0x2bb58c7d8, ...}, ...})
	/home/korniltsev/github/gotraceui/theme/window.go:165 +0x39
honnef.co/go/gotraceui/layout.PixelInset.Layout({0x467?, 0x3f8000003f800000?, 0xaed560?, 0xc0001b86d0?}, {{{0x750, 0x456}, {0x750, 0x456}}, {0x3f800000, 0x3f800000}, ...}, ...)
	/home/korniltsev/github/gotraceui/layout/layout.go:103 +0x316
honnef.co/go/gotraceui/theme.(*Window).Layout(0xc000188500, 0xc0000e0880, {{0xc1a0c8c1de7d36f2, 0x2bb58c7d8, 0x102d580}, {0x3f800000, 0x3f800000}, {0x750, 0x467}, {0x0, ...}, ...}, ...)
	/home/korniltsev/github/gotraceui/theme/window.go:288 +0x7d6
main.(*MainWindow).Run(0xc0000a9008)
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:819 +0x508
main.main.func2()
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:1416 +0x1c
created by main.main in goroutine 1
	/home/korniltsev/github/gotraceui/cmd/gotraceui/main.go:1415 +0x59d

```

This time I clicked "highlight spans" -> "General"
