### ISSUE TITLE
Crash loading large trace

### ISSUE THREAD

**Issue by felixge** [dominikh/gotraceui#54]
Just tried to use gotraceui (version eaf52f6bae8a0e7771dadfe73d5aae4ab5d4cfea) with a 280MB trace (15s of prod activity) and observed the crash below.

```
$ go run ./cmd/gotraceui/ 'large.trace'
panic: runtime error: index out of range [-1]

goroutine 8 [running]:
main.loadTrace({0x1051ec378?, 0x140000100a8?}, {0x1051ed888, 0x14000080900})
	/Users/felixge/go/src/github.com/dominikh/gotraceui/cmd/gotraceui/trace.go:815 +0x38fc
main.main.func2()
	/Users/felixge/go/src/github.com/dominikh/gotraceui/cmd/gotraceui/main.go:952 +0x1a4
created by main.main
	/Users/felixge/go/src/github.com/dominikh/gotraceui/cmd/gotraceui/main.go:944 +0x3c0
exit status 2
````

I can't share this trace, but I hope the stack trace gives enough context to be helpful.

Thanks for working on this ❤️

**Comment by dominikh** [comment]
Try updating to 83549e7e07c84d2542876ea4d9898041190f9bad (which I've just pushed). The bug was related to an experimental feature that uncovered a shortcoming in the trace parser and the feature has since been disabled. (It's unrelated to the size of the trace.)

**Comment by felixge** [comment]
Thanks for the fast response, that fixed it! 🥳
